[workspace]
members = ["crates/*", "web"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/exodirectory/exo"
homepage = "https://exodirectory.org"
